### PR TITLE
Added apache (httpd) haproxy and wordpress to GHA

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by whalelines** [comment]
Any idea what this will do to the timing of the meta build?

**Comment by LaurentGoderre** [comment]
@whalelines it will slow it down. Im not sure by how much though

**Comment by whalelines** [comment]
Right, and isn't it already failing to complete by the time the next one is scheduled?

**Comment by whalelines** [comment]
Well, it seems that issue has resolved.

**Review by whalelines — APPROVED** [review]
LGTM

**Comment by whalelines** [comment]
Have you tested timing locally?

**Comment by LaurentGoderre** [comment]
I never got anywhere near the time that the script takes on the build machine

**Comment by whalelines** [comment]
I mean relatively. So if adding these three images locally makes it go from 7 minutes to 20 minutes, we can estimate it increased the time about threefold on the Jenkins runner.

**Comment by LaurentGoderre** [comment]
😓 it increases 50%

Before:
```
.scripts/builds.sh sources.json > /dev/null  177.41s user 58.04s system 20% cpu 19:09.06 total
```

After:
```
.scripts/builds.sh sources.json > /dev/null  254.98s user 78.18s system 29% cpu 18:43.96 total
```

**Comment by LaurentGoderre** [comment]
Yeah. This almost completes the leaf docker managed ones so it would be a good point to address scaling as we bring in community ones.

**Comment by tianon** [comment]
With https://github.com/docker-library/meta-scripts/pull/5, this should be fine.

**Pull request merged**
